# Generated by Django 6.0.2 on 2026-02-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0003_pet_sexo"),
        ("veterinarios", "0002_alter_veterinario_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroVacina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("data", models.DateField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacinas",
                        to="pets.pet",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacinas",
                        to="veterinarios.veterinario",
                    ),
                ),
                (
                    "vacina",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vacinas.vacina",
                    ),
                ),
            ],
        ),
    ]
