# Generated by Django 6.0.2 on 2026-02-11 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacinas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovacina",
            name="data",
            field=models.DateField(default=datetime.date(2026, 2, 11)),
        ),
    ]
