# Generated by Django 6.0.2 on 2026-02-11 13:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacinas", "0002_alter_registrovacina_data"),
        ("veterinarios", "0002_alter_veterinario_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovacina",
            name="data",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="registrovacina",
            name="vacina",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vacinas.vacina",
            ),
        ),
        migrations.AlterField(
            model_name="registrovacina",
            name="veterinario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacinas",
                to="veterinarios.veterinario",
            ),
        ),
    ]
