# Generated by Django 6.0.2 on 2026-02-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacinas", "0003_alter_registrovacina_data_and_more"),
        ("veterinarios", "0003_veterinario_crmv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovacina",
            name="veterinario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_vacina",
                to="veterinarios.veterinario",
            ),
        ),
    ]
