# Generated by Django 6.0.2 on 2026-02-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacinas", "0004_alter_registrovacina_veterinario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrovacina",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="vacina",
            options={"ordering": ["-id"]},
        ),
    ]
