# Generated by Django 6.0.2 on 2026-02-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinarios", "0002_alter_veterinario_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinario",
            name="crmv",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
