# Generated by Django 6.0.2 on 2026-02-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinarios", "0003_veterinario_crmv"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinario",
            name="cpf",
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
