# Generated by Django 6.0.2 on 2026-02-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinarios", "0004_veterinario_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="veterinario",
            options={"ordering": ["-id"]},
        ),
    ]
