# Generated by Django 6.0.2 on 2026-02-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutor",
            options={"verbose_name": "Tutor", "verbose_name_plural": "Tutores"},
        ),
    ]
