# Generated by Django 6.0.2 on 2026-02-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0003_tutor_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutor",
            options={
                "ordering": ["-id"],
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
            },
        ),
    ]
