# Generated by Django 6.0.2 on 2026-02-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="raca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
