# Generated by Django 6.0.2 on 2026-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_alter_pet_raca"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Macho"), ("F", "Fêmea"), ("N", "Não Informado")],
                default="N",
                max_length=1,
            ),
        ),
    ]
