# Generated by Django 6.0.2 on 2026-02-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_pet_sexo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"ordering": ["-id"]},
        ),
    ]
